## Assignment on generating Random numbers

In [3]:
import random
numlst = list(range(10))
numlst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [82]:
def bsd_rand(seed):
    def rand():
        rand. seed = (1103515245*rand. seed + 12345) & 0x7fffffff
        return rand. seed
    rand. seed = seed
    return rand

In [83]:
#Genrating random numbers

class NotSoRandom(object):
    def seed(self, a=3):
        """Seed the world's most mysterious random number generator."""
        self.seedval = a
    def random(self):
        """Look, random numbers!"""
        self.seedval = (self.seedval * 3) % 19
        return self.seedval

_inst = NotSoRandom()
seed = _inst.seed
random = _inst.random

In [84]:
seed(1234)

In [86]:
a=random()
a

10

In [77]:
for i in a:
    print(i, end="")

11

In [87]:
seed(255)

In [88]:
#b=[random() for i in range(1)]
b=random()
b

5

In [80]:
for j in b:
    print(j, end="")

5

In [89]:
#binomial Distribution

import numpy as np
# initialize the seed to 25
np.random.seed(25)  # 10 number of trials with probability of 0.5 each
np.random.binomial(n=10, p=0.5, size=10)

array([7, 5, 4, 4, 5, 3, 6, 5, 5, 4])

In [90]:
# initialize the seed to 25
np.random.seed(25)  # degree of freedom 2 and size (2, 3)
np.random.chisquare(df=2, size=(2, 3))

array([[4.08235236, 1.74587315, 0.65378557],
       [0.41137173, 1.05899821, 0.24971095]])

In [91]:
#initialize the seed to 25
np.random.seed(25)
#Poisson Distribution
#rate 2 and size 10

np.random.poisson(lam=2, size=10)

array([3, 1, 3, 1, 2, 2, 3, 3, 0, 2])

In [94]:
#calculating pi values

from random import *  
from math import sqrt  
inside=0  
n=1000  
for i in range(0,n):  
    #x=random()  
    #y=random()  
    if sqrt(a*a+b*b)<=1:  
        inside+=1  
pi=4*inside/n  
print(pi)

0.0


In [93]:
# calculating pi values

from random import *  
from math import sqrt  
inside=0  
n=1000  
for i in range(0,n):  
    x=random()  
    y=random()  
    if sqrt(x*x+y*y)<=1:  
        inside+=1  
pi=4*inside/n  
print("pi",pi)
print("x=",x)
print("y=",y)

pi 3.112
x= 0.6155055691901605
y= 0.6477850131342445
